FROM openjdk:11

# Docker wait-for-it, used when there us dependency between containers
RUN apt update && \
    apt install -y wget netcat-traditional && \
    wget -q -O /usr/bin/wait-for https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for && \
    chmod +x /usr/bin/wait-for

WORKDIR /app

COPY fc-wallet-core-0.0.1-SNAPSHOT.jar .

CMD ["java","-jar","fc-wallet-core-0.0.1-SNAPSHOT.jar"]

EXPOSE 3002
